In [38]:
import numpy as np
from numpy import genfromtxt

data = genfromtxt('../data/bank_note_data.txt', delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [39]:
labels = data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [40]:
features = data[:, 0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [41]:
X = features
y = labels

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [44]:
len(X_train)

919

In [45]:
len(X)

1372

In [46]:
len(X_test)

453

In [47]:
from sklearn.preprocessing import MinMaxScaler

In [48]:
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [49]:
scaled_X_train = scaler_object.transform(X_train)

In [50]:
scaled_X_test = scaler_object.transform(X_test)

In [51]:
scaled_X_train.max()

1.0000000000000002

In [52]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [53]:
from keras.models import Sequential
from keras.layers import Dense

In [54]:
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [55]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [56]:
model.fit(scaled_X_train, y_train, epochs=500, verbose=2)

Epoch 1/500
 - 0s - loss: 0.6778 - acc: 0.5495
Epoch 2/500
 - 0s - loss: 0.6759 - acc: 0.5495
Epoch 3/500
 - 0s - loss: 0.6738 - acc: 0.5495
Epoch 4/500
 - 0s - loss: 0.6715 - acc: 0.5495
Epoch 5/500
 - 0s - loss: 0.6687 - acc: 0.5495
Epoch 6/500
 - 0s - loss: 0.6647 - acc: 0.5495
Epoch 7/500
 - 0s - loss: 0.6599 - acc: 0.5495
Epoch 8/500
 - 0s - loss: 0.6524 - acc: 0.5495
Epoch 9/500
 - 0s - loss: 0.6411 - acc: 0.5495
Epoch 10/500
 - 0s - loss: 0.6270 - acc: 0.5593
Epoch 11/500
 - 0s - loss: 0.6088 - acc: 0.6355
Epoch 12/500
 - 0s - loss: 0.5877 - acc: 0.7856
Epoch 13/500
 - 0s - loss: 0.5650 - acc: 0.8063
Epoch 14/500
 - 0s - loss: 0.5389 - acc: 0.8716
Epoch 15/500
 - 0s - loss: 0.5126 - acc: 0.8847
Epoch 16/500
 - 0s - loss: 0.4871 - acc: 0.8651
Epoch 17/500
 - 0s - loss: 0.4603 - acc: 0.8912
Epoch 18/500
 - 0s - loss: 0.4353 - acc: 0.8912
Epoch 19/500
 - 0s - loss: 0.4125 - acc: 0.8912
Epoch 20/500
 - 0s - loss: 0.3922 - acc: 0.8934
Epoch 21/500
 - 0s - loss: 0.3730 - acc: 0.8945
E

In [57]:
model.metrics_names

['loss', 'acc']

In [58]:
from sklearn.metrics import confusion_matrix, classification_report

In [60]:
predictions = model.predict_classes(scaled_X_test)
confusion_matrix(y_test, predictions)

array([[254,   3],
       [  2, 194]], dtype=int64)

In [61]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99       257
        1.0       0.98      0.99      0.99       196

avg / total       0.99      0.99      0.99       453



In [62]:
model.save('bank-model.h5')

In [64]:
# To reuse trained model:
from keras.models import load_model
model = load_model('bank-model.h5')